version: '3'
services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'friends-big-ball'
      MYSQL_USER: 'ewcode'
      MYSQL_PASSWORD: 'ewcode123'
      MYSQL_ROOT_PASSWORD: 'ewcode123'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata: