server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ewcode
    url: jdbc:mysql://localhost:3306/friends-big-ball?autoReconnect=true
    password: ewcode123
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  kafka:
    enabled: false
    bootstrap-servers: "192.168.15.168:29092"
    producer:
      bootstrap-servers: "192.168.15.168:29092"
    consumer:
      bootstrap-servers: "192.168.15.168:29092"
      auto-offset-reset: earliest